version: '3.8'

services:
  pcare-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - API_KEY=${API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo
    networks:
      - pcare-network

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: personal_care_app
    volumes:
      - mongo_data:/data/db
    networks:
      - pcare-network

  mongo-express:
    image: mongo-express:1.0.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
    networks:
      - pcare-network

volumes:
  mongo_data:

networks:
  pcare-network:
    driver: bridge
